/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import Koneksi.KoneksiDB;
import Logic.lapangan;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC-USER
 */
public class FLapangan extends javax.swing.JInternalFrame {
private DefaultTableModel tabmode;
private ResultSet RsLpg;
private String trans;
    /**
     * Creates new form FLapangan
     */
    public FLapangan() {
        initComponents();
        isiGrid();
        lapangan();
    }
    
    void emptyText(){
        TKode.setText("");
        TNama.setText("");
        THarga.setText("");
       // THargambr.setText("");
        
    }
    
    private void lapangan()
    {
       try {
            String sql="select * from lapangan order by kode desc";
            RsLpg = KoneksiDB.getRS(sql); 
            if (RsLpg.next()) {
                String Lpg = RsLpg.getString("kode").substring(3);
                String AN = "" + (Integer.parseInt(Lpg) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

               TKode.setText("KD-" + Nol + AN);
            } else {
               TKode.setText("KD-0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
     }

    private void isiGrid() {
        delGrid(TTable);
        DefaultTableModel defGrid = (DefaultTableModel) TTable.getModel();
        RsLpg = KoneksiDB.getRS("select * from lapangan");
        try {
            while (RsLpg.next()) {
                String[] data = {RsLpg.getString("kode"), RsLpg.getString("nama"),
                                 RsLpg.getString("harga"),RsLpg.getString("hargambr")};
                defGrid.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FLapangan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void delGrid(JTable gg) {
        DefaultTableModel defGrid = (DefaultTableModel) gg.getModel();
        int brs = gg.getRowCount();
        for(int i=0;i<brs;i++) {
            defGrid.removeRow(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TKode = new javax.swing.JTextField();
        TNama = new javax.swing.JTextField();
        THarga = new javax.swing.JTextField();
        THargambr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtcari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BSimpan = new rojerusan.RSButtonHover();
        BUbah = new rojerusan.RSButtonHover();
        Bhapus = new rojerusan.RSButtonHover();
        BBatal = new rojerusan.RSButtonHover();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Stadium_40px.png"))); // NOI18N
        jLabel1.setText("Input Data Lapangan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        TKode.setEditable(false);
        TKode.setBackground(new java.awt.Color(255, 255, 255));
        TKode.setForeground(new java.awt.Color(204, 0, 0));
        TKode.setBorder(null);
        TKode.setCaretColor(new java.awt.Color(204, 0, 0));
        TKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKodeActionPerformed(evt);
            }
        });

        TNama.setForeground(new java.awt.Color(204, 0, 0));
        TNama.setBorder(null);
        TNama.setCaretColor(new java.awt.Color(204, 0, 0));

        THarga.setForeground(new java.awt.Color(204, 0, 0));
        THarga.setBorder(null);
        THarga.setCaretColor(new java.awt.Color(204, 0, 0));

        THargambr.setEditable(false);
        THargambr.setBackground(new java.awt.Color(255, 255, 255));
        THargambr.setForeground(new java.awt.Color(204, 0, 0));
        THargambr.setText("Mendapat Diskon");
        THargambr.setBorder(null);
        THargambr.setCaretColor(new java.awt.Color(204, 0, 0));

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Kode");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Nama Lapangan");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Harga");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Harga Member");

        jSeparator2.setForeground(new java.awt.Color(204, 51, 0));

        jSeparator3.setForeground(new java.awt.Color(204, 51, 0));

        jSeparator4.setForeground(new java.awt.Color(204, 51, 0));

        jSeparator5.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator5)
                    .addComponent(TKode, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(THargambr, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(TNama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(THarga, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(THarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(THargambr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        TTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Lapangan", "Harga", "Harga Member"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TTable);

        jSeparator1.setForeground(new java.awt.Color(204, 51, 0));

        txtcari.setForeground(new java.awt.Color(204, 0, 0));
        txtcari.setBorder(null);
        txtcari.setCaretColor(new java.awt.Color(204, 0, 0));
        txtcari.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Search_16px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        BSimpan.setBackground(new java.awt.Color(204, 0, 0));
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Save_16px.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setColorHover(new java.awt.Color(255, 51, 0));
        BSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BUbah.setBackground(new java.awt.Color(204, 0, 0));
        BUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Renew Subscription_16px.png"))); // NOI18N
        BUbah.setText("Ubah");
        BUbah.setColorHover(new java.awt.Color(255, 51, 0));
        BUbah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        Bhapus.setBackground(new java.awt.Color(204, 0, 0));
        Bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Delete_16px.png"))); // NOI18N
        Bhapus.setText("Hapus");
        Bhapus.setColorHover(new java.awt.Color(255, 51, 0));
        Bhapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });

        BBatal.setBackground(new java.awt.Color(204, 0, 0));
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Cancel_16px.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.setColorHover(new java.awt.Color(255, 51, 0));
        BBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKodeActionPerformed

    }//GEN-LAST:event_TKodeActionPerformed

    private void TTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTableMouseClicked
        // TODO add your handling code here:
        if (lapangan.carilapangan(TTable.getValueAt
            (TTable.getSelectedRow(),0).toString())==true) {
        TKode.setText(lapangan.getKode());
        TNama.setText(lapangan.getNama());
        THarga.setText(lapangan.getHarga());
        THargambr.setText(lapangan.getHargambr());
        }

    }//GEN-LAST:event_TTableMouseClicked

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        trans="tambah";
        String[] plg={TKode.getText(),TNama.getText(),THarga.getText(),THargambr.getText()};
            if (lapangan.updatelapangan(trans,plg)>0){
                javax.swing.JOptionPane.showMessageDialog(this, "Data Lapangan Telah Disimpan");
                emptyText();
                isiGrid();
                }
            else{javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
                               
                }
            lapangan();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        trans="ubah";
        String[] plg={TKode.getText(),TNama.getText(),THarga.getText(),THargambr.getText()};
            if (lapangan.updatelapangan(trans,plg)>0){
                javax.swing.JOptionPane.showMessageDialog(this, "Data Lapangan Telah Diubah");
                emptyText();
                isiGrid();
                }
            else{javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
                               
            }
        lapangan();
    }//GEN-LAST:event_BUbahActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        trans = "hapus";
        String[] plg = {TKode.getText()};
        if(javax.swing.JOptionPane.showConfirmDialog(this,
                "Anda yakin akan menghapus data ini ?", "Hati-hati !",
                javax.swing.JOptionPane.YES_NO_OPTION)==0) {
            if(lapangan.updatelapangan(trans, plg)>0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Lapangan Telah Terhapus");
                emptyText();
                isiGrid();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        lapangan();
        }
    }//GEN-LAST:event_BhapusActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        emptyText();
        lapangan();
    }//GEN-LAST:event_BBatalActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        Object[] Baris ={"Kode","Nama Lapangan","Harga","Harga Member"}; 
           tabmode = new DefaultTableModel(null, Baris); 
            String cariitem=txtcari.getText(); 
            
             try { 
                  String sql = "SELECT * FROM lapangan where kode like '%"+cariitem+"%' or nama like"
                          + "'%"+cariitem+"%' order by kode asc"; 
                    RsLpg = KoneksiDB.getRS(sql); 
                      while (RsLpg.next()){
                           tabmode.addRow(new Object[]{
                            RsLpg.getString(1),
                            RsLpg.getString(2),
                            RsLpg.getString(3),
                            RsLpg.getString(4),
                            RsLpg.getString(5)
                            });
                      }
                      TTable.setModel(tabmode);
             } catch (Exception e) {
             lapangan();
             }
        }
    }//GEN-LAST:event_txtcariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover BBatal;
    private rojerusan.RSButtonHover BSimpan;
    private rojerusan.RSButtonHover BUbah;
    private rojerusan.RSButtonHover Bhapus;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField THargambr;
    private javax.swing.JTextField TKode;
    private javax.swing.JTextField TNama;
    private javax.swing.JTable TTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
