/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC-USER
 */
public class FLaporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FLaporan
     */
    public FLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BCetak = new rojerusan.RSButtonHover();
        BCetak1 = new rojerusan.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BCetak2 = new rojerusan.RSButtonHover();
        BCetak3 = new rojerusan.RSButtonHover();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Report Card_40px.png"))); // NOI18N
        jLabel1.setText("Laporan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Laporan Bulanan");

        BCetak.setBackground(new java.awt.Color(204, 0, 0));
        BCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Print_16px.png"))); // NOI18N
        BCetak.setText("Cetak");
        BCetak.setColorHover(new java.awt.Color(255, 51, 0));
        BCetak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetakActionPerformed(evt);
            }
        });

        BCetak1.setBackground(new java.awt.Color(204, 0, 0));
        BCetak1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Print_16px.png"))); // NOI18N
        BCetak1.setText("Cetak");
        BCetak1.setColorHover(new java.awt.Color(255, 51, 0));
        BCetak1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetak1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Laporan Data Tim");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Laporan Data Alat");

        BCetak2.setBackground(new java.awt.Color(204, 0, 0));
        BCetak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Print_16px.png"))); // NOI18N
        BCetak2.setText("Cetak");
        BCetak2.setColorHover(new java.awt.Color(255, 51, 0));
        BCetak2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetak2ActionPerformed(evt);
            }
        });

        BCetak3.setBackground(new java.awt.Color(204, 0, 0));
        BCetak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Print_16px.png"))); // NOI18N
        BCetak3.setText("Cetak");
        BCetak3.setColorHover(new java.awt.Color(255, 51, 0));
        BCetak3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BCetak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetak3ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Laporan Pemesanan");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Conference_35px.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Soccer Ball_35px.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Ticket_40px.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Report Card_37px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(BCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addGap(101, 101, 101)
                .addComponent(jLabel7)
                .addGap(104, 104, 104)
                .addComponent(jLabel8)
                .addGap(80, 80, 80)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetakActionPerformed
        try{
            String Response = JOptionPane.showInputDialog(null, "Masukkan Bulan","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            String Response1 = JOptionPane.showInputDialog(null, "Masukkan Tahun","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            String NamaFile = "./src/laporan/RBulan.jasper";
            String Logo = new File("src\\Gambar\\logo1.png").getAbsolutePath();
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/futsal","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("futsal",Logo);
            param.put("pbulan",Response);
            param.put("ptahun",Response1);

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BCetakActionPerformed

    private void BCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetak1ActionPerformed
        try{
            String Response2 = JOptionPane.showInputDialog(null, "Status Tim","Laporan Data Tim",JOptionPane.QUESTION_MESSAGE);
            String NamaFile = "./src/laporan/RDatatim.jasper";
            String Logo = new File("src\\Gambar\\logo1.png").getAbsolutePath();
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/futsal","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("futsal",Logo);
            param.put("status",Response2);

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BCetak1ActionPerformed

    private void BCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetak2ActionPerformed
        try{
            String Logo = new File("src\\Gambar\\logo1.png").getAbsolutePath();
            String NamaFile = "./src/Laporan/RDataalat.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/futsal","root","");
            HashMap param = new HashMap();
            
            param.put("futsal",Logo);
                   
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_BCetak2ActionPerformed

    private void BCetak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetak3ActionPerformed
        try{
            String Response = JOptionPane.showInputDialog(null, "Masukkan Bulan","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            String Response1 = JOptionPane.showInputDialog(null, "Masukkan Tahun","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            String Logo = new File("src\\Gambar\\logo1.png").getAbsolutePath();
            String NamaFile = "./src/laporan/RPemesanan.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/futsal","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("futsal",Logo);
            param.put("pbulan",Response);
            param.put("ptahun",Response1);

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BCetak3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover BCetak;
    private rojerusan.RSButtonHover BCetak1;
    private rojerusan.RSButtonHover BCetak2;
    private rojerusan.RSButtonHover BCetak3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
