/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

import Koneksi.KoneksiDB;
import Logic.team;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PC-USER
 */
public class FTim extends javax.swing.JInternalFrame {
private DefaultTableModel tabmode;
private ResultSet RsMbr;
private String trans;
    /**
     * Creates new form FTim
     */
    public FTim() {
        initComponents();
        isiGrid();
        member();
    }
    
    void emptyText(){
        TMember2.setText("");
        TNama2.setText("");
        TAlamat2.setText("");
        TTlp2.setText("");
        BGStatus.clearSelection();
    }
    
    private void member()
    {
       try {
            String sql="select * from  team order by kode desc";
            RsMbr = KoneksiDB.getRS(sql); 
            if (RsMbr.next()) {
                String team = RsMbr.getString("kode").substring(3);
                String AN = "" + (Integer.parseInt(team) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}

               TMember2.setText("MB-" + Nol + AN);
            } else {
               TMember2.setText("MB-0001");
            }

           }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
           }
     }
    
    private void isiGrid() {
        delGrid(TTable2);
        DefaultTableModel defGrid = (DefaultTableModel) TTable2.getModel();
        RsMbr = KoneksiDB.getRS("select * from team");
        try {
            while (RsMbr.next()) {
                String[] data = {RsMbr.getString("kode"), RsMbr.getString("nama"),
                                 RsMbr.getString("alamat"),RsMbr.getString("notlp"),
                                RsMbr.getString("status")};
                defGrid.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FTim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void delGrid(JTable gg) {
        DefaultTableModel defGrid = (DefaultTableModel) gg.getModel();
        int brs = gg.getRowCount();
        for(int i=0;i<brs;i++) {
            defGrid.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGStatus = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TMember2 = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TTlp2 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TAlamat2 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        mmbr2 = new javax.swing.JRadioButton();
        biasa2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        BSimpan = new rojerusan.RSButtonHover();
        Bhapus = new rojerusan.RSButtonHover();
        BUbah = new rojerusan.RSButtonHover();
        BBatal = new rojerusan.RSButtonHover();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        TNama2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        TTable2 = new javax.swing.JTable();
        Bcetak = new rojerusan.RSButtonHover();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Id");

        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Nama Team");

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Alamat");

        TMember2.setEditable(false);
        TMember2.setBackground(new java.awt.Color(255, 255, 255));
        TMember2.setForeground(new java.awt.Color(204, 0, 0));
        TMember2.setBorder(null);
        TMember2.setCaretColor(new java.awt.Color(204, 0, 0));
        TMember2.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtcari.setForeground(new java.awt.Color(204, 0, 0));
        txtcari.setBorder(null);
        txtcari.setCaretColor(new java.awt.Color(204, 0, 0));
        txtcari.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("No Telepon");

        TTlp2.setForeground(new java.awt.Color(204, 0, 0));
        TTlp2.setBorder(null);
        TTlp2.setCaretColor(new java.awt.Color(204, 0, 0));
        TTlp2.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        TAlamat2.setColumns(20);
        TAlamat2.setForeground(new java.awt.Color(204, 0, 0));
        TAlamat2.setRows(5);
        TAlamat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        TAlamat2.setCaretColor(new java.awt.Color(204, 0, 0));
        jScrollPane6.setViewportView(TAlamat2);

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Status");

        mmbr2.setBackground(new java.awt.Color(255, 255, 255));
        BGStatus.add(mmbr2);
        mmbr2.setForeground(new java.awt.Color(204, 0, 0));
        mmbr2.setText("Member");

        biasa2.setBackground(new java.awt.Color(255, 255, 255));
        BGStatus.add(biasa2);
        biasa2.setForeground(new java.awt.Color(204, 0, 0));
        biasa2.setText("Biasa");

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DATA TEAM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel19)
                .addContainerGap(825, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        BSimpan.setBackground(new java.awt.Color(204, 0, 0));
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Save_16px.png"))); // NOI18N
        BSimpan.setText("Simpan");
        BSimpan.setColorHover(new java.awt.Color(255, 51, 0));
        BSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        Bhapus.setBackground(new java.awt.Color(204, 0, 0));
        Bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Delete_16px.png"))); // NOI18N
        Bhapus.setText("Hapus");
        Bhapus.setColorHover(new java.awt.Color(255, 51, 0));
        Bhapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });

        BUbah.setBackground(new java.awt.Color(204, 0, 0));
        BUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Renew Subscription_16px.png"))); // NOI18N
        BUbah.setText("Ubah");
        BUbah.setColorHover(new java.awt.Color(255, 51, 0));
        BUbah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUbahActionPerformed(evt);
            }
        });

        BBatal.setBackground(new java.awt.Color(204, 0, 0));
        BBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Cancel_16px.png"))); // NOI18N
        BBatal.setText("Batal");
        BBatal.setColorHover(new java.awt.Color(255, 51, 0));
        BBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBatalActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(204, 51, 0));

        jSeparator3.setForeground(new java.awt.Color(204, 51, 0));

        jSeparator4.setForeground(new java.awt.Color(204, 51, 0));

        TNama2.setForeground(new java.awt.Color(204, 51, 0));
        TNama2.setBorder(null);
        TNama2.setCaretColor(new java.awt.Color(204, 51, 0));
        TNama2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TNama2KeyPressed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 51, 0));

        TTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Team", "Alamat", "No Telepon", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTable2TTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TTable2);

        Bcetak.setBackground(new java.awt.Color(204, 0, 0));
        Bcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Print_16px.png"))); // NOI18N
        Bcetak.setText("Cetak");
        Bcetak.setColorHover(new java.awt.Color(255, 51, 0));
        Bcetak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcetakActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Search_16px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(BSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(579, 579, 579))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TMember2)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(mmbr2)
                                        .addGap(34, 34, 34)
                                        .addComponent(biasa2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TTlp2)
                                    .addComponent(TNama2)
                                    .addComponent(jSeparator3)
                                    .addComponent(jScrollPane6)
                                    .addComponent(jSeparator4))))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(650, 650, 650))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TMember2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TTlp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(mmbr2)
                            .addComponent(biasa2)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(BUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TTable2TTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTable2TTableMouseClicked
        int baris= TTable2.getSelectedRow();
        if (team.carimember(TTable2.getValueAt
            (TTable2.getSelectedRow(),0).toString())==true) {
        TMember2.setText(team.getKode());
        TNama2.setText(team.getNama());
        TAlamat2.setText(team.getAlamat());
        TTlp2.setText(team.getNotlp());
        if("Member".equals(TTable2.getValueAt(baris,4).toString())){
            mmbr2.setSelected(true);
        }else{
            biasa2.setSelected(true);
        }
        }
    }//GEN-LAST:event_TTable2TTableMouseClicked

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        String status="";
        if  (mmbr2.isSelected())
        {   status="Member";
        }
        else if (biasa2.isSelected())
        {   status="Biasa";
        }
        trans="tambah";
        String[] plg = {TMember2.getText(), TNama2.getText(), TAlamat2.getText(),TTlp2.getText(),status};
        if(team.updatemember(trans, plg)>0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Tim Tersimpan");
            emptyText();
            isiGrid();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        member();
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        trans = "hapus";
        String[] plg = {TMember2.getText()};
        if(javax.swing.JOptionPane.showConfirmDialog(this,
            "Anda yakin akan menghapus data ini ?", "Hati-hati !",
            javax.swing.JOptionPane.YES_NO_OPTION)==0) {
        if(team.updatemember(trans, plg)>0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Tim Terhapus");
            emptyText();
            isiGrid();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        member();
        }
    }//GEN-LAST:event_BhapusActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        String status="";
        if  (mmbr2.isSelected())
        {   status="Member";
        }
        else if (biasa2.isSelected())
        {   status="Biasa";
        }
        trans="ubah";
        String[] plg = {TMember2.getText(),TNama2.getText(), TAlamat2.getText(),TTlp2.getText(),status};
        if(team.updatemember(trans, plg)>0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Tim Telah Diubah");
            emptyText();
            isiGrid();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan, Silahkan coba lagi", "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        member();
    }//GEN-LAST:event_BUbahActionPerformed

    private void BBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBatalActionPerformed
        emptyText();
        member();
    }//GEN-LAST:event_BBatalActionPerformed

    private void TNama2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TNama2KeyPressed
        
    }//GEN-LAST:event_TNama2KeyPressed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed

    }//GEN-LAST:event_txtcariActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            Object[] Baris ={"Id","Nama Team","Alamat","No Telepon","Status"};
            tabmode = new DefaultTableModel(null, Baris);
            String cariitem=txtcari.getText();

            try {
                String sql = "SELECT * FROM team where kode like '%"+cariitem+"%' or nama like"
                + "'%"+cariitem+"%' order by kode asc";
                RsMbr = KoneksiDB.getRS(sql);
                while (RsMbr.next()){
                    tabmode.addRow(new Object[]{
                        RsMbr.getString(1),
                        RsMbr.getString(2),
                        RsMbr.getString(3),
                        RsMbr.getString(4),
                        RsMbr.getString(5)
                    });
                }
                TTable2.setModel(tabmode);
            } catch (Exception e) {
                member();
            }
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void BcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcetakActionPerformed
        try{
            String Logo = new File("src\\Gambar\\logo1.png").getAbsolutePath();
            String NamaFile = "./src/laporan/kartumember.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/futsal","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("futsal",Logo);
            param.put("TGL",txtcari.getText());

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BcetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover BBatal;
    private javax.swing.ButtonGroup BGStatus;
    private rojerusan.RSButtonHover BSimpan;
    private rojerusan.RSButtonHover BUbah;
    private rojerusan.RSButtonHover Bcetak;
    private rojerusan.RSButtonHover Bhapus;
    private javax.swing.JTextArea TAlamat2;
    private javax.swing.JTextField TMember2;
    private javax.swing.JTextField TNama2;
    private javax.swing.JTable TTable2;
    private javax.swing.JTextField TTlp2;
    private javax.swing.JRadioButton biasa2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton mmbr2;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
